language: lisp

env:
  matrix:
    - LISP=abcl
    - LISP=sbcl
    - LISP=ccl
    - LISP=clisp
    - LISP=cmucl
    - LISP=ecl

install:
  - curl https://raw2.github.com/luismbo/cl-travis/master/install.sh | bash

script:
  - cl-launch -i "(ql:quickload :cl-html5-parser) (ql:quickload :cl-html5-parser-tests) (html5-parser-tests::run-html5-parser-tests)"
