language: lisp

env:
  matrix:
    - LISP=sbcl
    - LISP=ecl

install:
  - curl https://raw2.github.com/luismbo/cl-travis/master/install.sh | bash

script:
  - cl-launch -i "(ql:quickload :cl-html5-parser-tests) (ql:quickload :cl-html5-parser-tests)"
